import { NextRequest, NextResponse } from "next/server";
import Groq from "groq-sdk";

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

// HARDCODED config files - AI never touches these
const CONFIG_FILES = [
  {
    filename: "package.json",
    content: JSON.stringify({
      name: "my-app",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: { next: "14.2.5", react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: {
        "@types/node": "^20", "@types/react": "^18",
        "@types/react-dom": "^18", typescript: "^5",
        tailwindcss: "^3.4.1", autoprefixer: "^10.0.1", postcss: "^8"
      }
    }, null, 2)
  },
  {
    filename: "tsconfig.json",
    content: JSON.stringify({
      compilerOptions: {
        target: "es5", lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true, skipLibCheck: true, strict: true,
        noEmit: true, esModuleInterop: true, module: "esnext",
        moduleResolution: "bundler", resolveJsonModule: true,
        isolatedModules: true, jsx: "preserve", incremental: true,
        plugins: [{ name: "next" }], paths: { "@/*": ["./src/*"] }
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      exclude: ["node_modules"]
    }, null, 2)
  },
  {
    filename: "tailwind.config.ts",
    content: `import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [],
};
export default config;`
  },
  {
    filename: "postcss.config.js",
    content: `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }`
  },
  {
    filename: "next.config.js",
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig`
  },
  {
    filename: "src/app/globals.css",
    content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`
  },
  {
    filename: "src/app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = { title: "My App", description: "Generated by Grace" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body className="bg-gray-950 text-white min-h-screen">{children}</body></html>;
}`
  },
];

export async function POST(req: NextRequest) {
  try {
    const { idea, features, industry, audience, projectName } = await req.json();

    if (!idea) {
      return NextResponse.json({ error: "No idea provided" }, { status: 400 });
    }

    // Only ask AI to generate the actual app page
    const prompt = `You are an expert React developer. Generate a single complete page.tsx file for a Next.js app.

Project: ${projectName}
Idea: ${idea}
Industry: ${industry}
Audience: ${audience}
Features: ${features.join(", ")}

Generate ONLY the content for src/app/page.tsx.

REQUIREMENTS:
- Start with "use client";
- Import ONLY useState from "react" - nothing else
- Dark theme with beautiful gradients
- Navbar with app name and navigation that works with useState
- Hero section with headline and CTA
- All features implemented: ${features.join(", ")}
- Every button must work using useState
- Use realistic dummy data
- Beautiful Tailwind CSS classes
- At least 400 lines of code
- NO external imports
- NO missing dependencies
- Professional and modern design

Return ONLY the raw TypeScript code for page.tsx.
No explanation. No markdown. Just the code starting with "use client";`;

    const response = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: "You are an expert React developer. Return ONLY raw TypeScript/TSX code. No markdown. No backticks. No explanation. Just the code.",
        },
        { role: "user", content: prompt }
      ],
      max_tokens: 8000,
      temperature: 0.2,
    });

    let pageContent = response.choices[0].message.content || "";
    
    // Clean up any markdown backticks if present
    pageContent = pageContent
      .replace(/```tsx/g, "")
      .replace(/```typescript/g, "")
      .replace(/```/g, "")
      .trim();

    // Update package.json name
    const files = CONFIG_FILES.map(f => {
      if (f.filename === "package.json") {
        const pkg = JSON.parse(f.content);
        pkg.name = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
        return { ...f, content: JSON.stringify(pkg, null, 2) };
      }
      if (f.filename === "src/app/layout.tsx") {
        return {
          ...f,
          content: f.content
            .replace("My App", projectName)
            .replace("Generated by Grace", idea)
        };
      }
      return f;
    });

    // Fix common AI mistakes
if (!pageContent.startsWith('"use client"')) {
  pageContent = pageContent.replace(/^use client;?/m, '"use client";');
  if (!pageContent.includes('"use client"')) {
    pageContent = '"use client";\n' + pageContent;
  }
}

files.push({
  filename: "src/app/page.tsx",
  content: pageContent,
});
    return NextResponse.json({ files });

  } catch (error) {
    console.error("Groq API error:", error);
    return NextResponse.json({ error: "Generation failed" }, { status: 500 });
  }
}