import { NextRequest, NextResponse } from "next/server";
import Groq from "groq-sdk";

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

// HARDCODED config files - AI never touches these
const CONFIG_FILES = [
  {
    filename: "package.json",
    content: JSON.stringify({
      name: "my-app",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: { next: "14.2.5", react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: {
        "@types/node": "^20", "@types/react": "^18",
        "@types/react-dom": "^18", typescript: "^5",
        tailwindcss: "^3.4.1", autoprefixer: "^10.0.1", postcss: "^8"
      }
    }, null, 2)
  },
  {
    filename: "tsconfig.json",
    content: JSON.stringify({
      compilerOptions: {
        target: "es5", lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true, skipLibCheck: true, strict: true,
        noEmit: true, esModuleInterop: true, module: "esnext",
        moduleResolution: "bundler", resolveJsonModule: true,
        isolatedModules: true, jsx: "preserve", incremental: true,
        plugins: [{ name: "next" }], paths: { "@/*": ["./src/*"] }
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      exclude: ["node_modules"]
    }, null, 2)
  },
  {
    filename: "tailwind.config.ts",
    content: `import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [],
};
export default config;`
  },
  {
    filename: "postcss.config.js",
    content: `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }`
  },
  {
    filename: "next.config.js",
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig`
  },
  {
    filename: "src/app/globals.css",
    content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`
  },
  {
    filename: "src/app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = { title: "My App", description: "Generated by Grace" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body className="bg-gray-950 text-white min-h-screen">{children}</body></html>;
}`
  },
];

export async function POST(req: NextRequest) {
  try {
    const { idea, features, industry, audience, projectName } = await req.json();

    if (!idea) {
      return NextResponse.json({ error: "No idea provided" }, { status: 400 });
    }

    // Only ask AI to generate the actual app page
   const prompt = `You are an expert React developer. Generate a STUNNING, FULLY FUNCTIONAL single page app.

Project: ${projectName}
Core Idea: ${idea}
Industry: ${industry}
Audience: ${audience}
Features requested: ${features.join(", ")}

THE MOST IMPORTANT THING:
Build the ACTUAL app the user described: "${idea}"
Not a generic landing page. The REAL working app.

For example:
- Event Planner → Show actual events list, create event form, calendar view
- Expense Tracker → Show actual expenses table, add expense form, charts
- Job Board → Show actual job listings, apply button, filters
- Fitness Planner → Show actual workout plans, exercise list, progress

STRUCTURE THE APP LIKE THIS:

1. NAVBAR - App name + navigation tabs for each feature
2. MAIN CONTENT - Changes based on active tab using useState
3. Each tab shows the REAL feature:

For features: ${features.join(", ")} build these exact sections:

${features.map((f: string) => `- ${f} section: Show real UI for ${f} with dummy data, forms, buttons`).join("\n")}

TECHNICAL REQUIREMENTS:
- "use client"; at the very top (with quotes!)
- import { useState } from "react"; 
- Dark theme: bg-gray-900, bg-gray-800 for cards
- Blue/cyan accents: text-blue-400, bg-blue-500, border-blue-500
- Beautiful gradient header: bg-gradient-to-r from-blue-600 to-cyan-600
- Realistic dummy data (at least 5-8 items per list)
- Working forms with useState
- Working modals with useState  
- Working filters/search with useState
- Tables with real columns and data
- Status badges with colors
- Action buttons (Edit, Delete, View) that update state
- Minimum 500 lines of code
- NO external imports except useState from react

DUMMY DATA EXAMPLES:
- Names: use realistic names like "Sarah Johnson", "Tech Conference 2026"
- Dates: use realistic dates like "March 25, 2026"
- Prices: use realistic prices like "$299", "₹2,500"
- Status: use colored badges like "Active"=green, "Pending"=yellow, "Done"=blue

Return ONLY the raw TSX code. No markdown. No backticks. Start with "use client";`;

    const response = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: "You are an expert React developer. Return ONLY raw TypeScript/TSX code. No markdown. No backticks. No explanation. Just the code.",
        },
        { role: "user", content: prompt }
      ],
      max_tokens: 8000,
      temperature: 0.2,
    });

    let pageContent = response.choices[0].message.content || "";
    
    // Clean up any markdown backticks if present
    pageContent = pageContent
      .replace(/```tsx/g, "")
      .replace(/```typescript/g, "")
      .replace(/```/g, "")
      .trim();

    // Update package.json name
    const files = CONFIG_FILES.map(f => {
      if (f.filename === "package.json") {
        const pkg = JSON.parse(f.content);
        pkg.name = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
        return { ...f, content: JSON.stringify(pkg, null, 2) };
      }
      if (f.filename === "src/app/layout.tsx") {
        return {
          ...f,
          content: f.content
            .replace("My App", projectName)
            .replace("Generated by Grace", idea)
        };
      }
      return f;
    });

    // Fix common AI mistakes
if (!pageContent.startsWith('"use client"')) {
  pageContent = pageContent.replace(/^use client;?/m, '"use client";');
  if (!pageContent.includes('"use client"')) {
    pageContent = '"use client";\n' + pageContent;
  }
}

files.push({
  filename: "src/app/page.tsx",
  content: pageContent,
});
    return NextResponse.json({ files });

  } catch (error) {
    console.error("Groq API error:", error);
    return NextResponse.json({ error: "Generation failed" }, { status: 500 });
  }
}
